import { Router } from 'express';

/**
 * FliDeck capabilities description for agent discovery.
 * Agents can query this endpoint to understand what FliDeck offers
 * without needing embedded documentation.
 */
const CAPABILITIES = {
  name: 'FliDeck Presentation Server',
  version: '0.2.0',
  description:
    'A local-first presentation viewer that discovers, organizes, and displays HTML slides generated by AI agents.',

  concepts: {
    presentation: {
      summary: 'A folder containing HTML slides and an index.json manifest',
      details:
        'Each presentation is a directory under the configured presentationsRoot. FliDeck discovers presentations automatically by looking for folders containing HTML files.',
    },
    tab: {
      summary: 'A perspective or persona view within a presentation',
      details:
        "Tabs allow one presentation to have multiple entry points. Each tab has its own index HTML file (e.g., index-mary.html). When a user clicks a tab, they see that tab's index and the sidebar filters to show only slides belonging to that tab.",
      when_to_use:
        'Use tabs when a presentation has content for different audiences (e.g., personas like Mary, John) or different aspects (e.g., Overview, Deep Dive).',
    },
    group: {
      summary: 'A collection of related slides shown as a collapsible section',
      details:
        'Groups organize slides in the sidebar. A group can optionally belong to a tab via the tabId property. Groups without tabId appear in all tabs.',
      when_to_use: 'Use groups when you have 15+ slides that benefit from organization.',
    },
    slide: {
      summary: 'An individual HTML file displayed in the viewer',
      details:
        'Slides are the core content. They can be standalone or assigned to groups. FliDeck discovers slides from the filesystem but prefers metadata from the manifest.',
    },
    manifest: {
      summary: 'The index.json file that defines presentation structure',
      details:
        'The manifest is the source of truth for tabs, groups, slide metadata, and ordering. FliDeck APIs update the manifest. Changes trigger real-time UI updates via WebSocket.',
    },
  },

  common_workflows: {
    add_slide_to_presentation: {
      description: 'Add a new slide to an existing presentation',
      steps: [
        '1. Write your HTML slide file to the presentation folder',
        "2. Call POST /api/presentations/{id}/slides with { file: 'yourslide.html', group?: 'group-id', title?: 'Display Name' }",
        '3. FliDeck updates the manifest and notifies connected clients',
      ],
      example: {
        method: 'POST',
        url: '/api/presentations/my-deck/slides',
        body: { file: 'new-feature.html', group: 'features', title: 'New Feature Overview' },
      },
    },
    create_tabbed_presentation: {
      description: 'Create a presentation with multiple perspectives/personas',
      steps: [
        '1. Create the presentation folder with slides',
        '2. Create index-{tabId}.html files for each tab (e.g., index-mary.html)',
        '3. Call POST /api/presentations/{id}/tabs for each tab',
        '4. Create groups with tabId assignments',
        '5. Assign slides to groups',
      ],
      example: {
        method: 'POST',
        url: '/api/presentations/my-deck/tabs',
        body: { id: 'mary', label: "Mary's View" },
      },
    },
    sync_manifest_with_filesystem: {
      description: 'Auto-discover slides and update manifest',
      steps: [
        '1. Call PUT /api/presentations/{id}/manifest/sync with options',
        '2. FliDeck scans filesystem for HTML files',
        '3. Manifest is updated with discovered slides',
      ],
      example: {
        method: 'PUT',
        url: '/api/presentations/my-deck/manifest/sync',
        body: { strategy: 'merge', inferGroups: true, inferTitles: true },
      },
    },
    sync_from_index_html: {
      description: 'Parse an index HTML file to populate manifest (self-healing)',
      steps: [
        '1. Call PUT /api/presentations/{id}/manifest/sync-from-index',
        '2. FliDeck parses the index HTML for slide links and groupings',
        '3. Manifest is updated with discovered structure',
      ],
      example: {
        method: 'PUT',
        url: '/api/presentations/my-deck/manifest/sync-from-index',
        body: { source: 'index.html', strategy: 'merge' },
      },
    },
    query_current_state: {
      description: 'Get the current state of a presentation',
      steps: [
        '1. Call GET /api/presentations/{id}',
        '2. Response includes tabs, groups, slides, and metadata',
      ],
      example: {
        method: 'GET',
        url: '/api/presentations/my-deck',
      },
    },
  },

  api_summary: {
    health: {
      'GET /api/health': 'Check if FliDeck is running',
    },
    capabilities: {
      'GET /api/capabilities': 'Discover FliDeck capabilities (this endpoint)',
    },
    presentations: {
      'GET /api/presentations': 'List all presentations',
      'GET /api/presentations/:id': 'Get single presentation with full data',
      'POST /api/presentations': 'Create new presentation',
    },
    manifest: {
      'GET /api/presentations/:id/manifest': 'Get raw manifest JSON',
      'PUT /api/presentations/:id/manifest': 'Replace entire manifest',
      'PATCH /api/presentations/:id/manifest': 'Partial manifest update',
    },
    slides: {
      'POST /api/presentations/:id/slides': 'Add slide to manifest',
      'PUT /api/presentations/:id/slides/:slideId': 'Update slide metadata',
      'DELETE /api/presentations/:id/slides/:slideId': 'Remove slide from manifest',
    },
    tabs: {
      'POST /api/presentations/:id/tabs': 'Create tab',
      'PUT /api/presentations/:id/tabs/:tabId': 'Rename tab',
      'DELETE /api/presentations/:id/tabs/:tabId': 'Delete tab',
      'PUT /api/presentations/:id/tabs/order': 'Reorder tabs',
    },
    groups: {
      'POST /api/presentations/:id/groups': 'Create group',
      'PUT /api/presentations/:id/groups/:groupId': 'Rename group',
      'DELETE /api/presentations/:id/groups/:groupId': 'Delete group',
      'PUT /api/presentations/:id/groups/:groupId/parent': 'Assign group to tab',
      'DELETE /api/presentations/:id/groups/:groupId/parent': 'Remove group from tab',
    },
    bulk_operations: {
      'POST /api/presentations/:id/manifest/slides/bulk': 'Add multiple slides',
      'PUT /api/presentations/:id/manifest/sync': 'Sync manifest with filesystem',
      'PUT /api/presentations/:id/manifest/sync-from-index': 'Parse index HTML to populate manifest',
      'POST /api/presentations/:id/manifest/validate': 'Validate manifest',
    },
    schema: {
      'GET /api/schema/manifest': 'Get JSON Schema for manifest validation',
    },
    templates: {
      'GET /api/templates/manifest': 'List available manifest templates',
      'GET /api/templates/manifest/:id': 'Get specific template',
      'POST /api/presentations/:id/manifest/template': 'Apply template to presentation',
    },
  },

  tips: [
    'Always check GET /api/health first to confirm FliDeck is running',
    'Use GET /api/presentations/:id to understand current state before making changes',
    'Prefer API calls over direct file writes - FliDeck validates and broadcasts changes',
    'If FliDeck is offline, you can write index.json directly as fallback',
    'Tab-specific slides need: tab → group with tabId → slide in group',
    'Slides without groups appear in ALL tabs (root assets)',
    'Use sync-from-index to recover structure from an index HTML file',
  ],

  documentation: {
    knowledge_base: 'docs/architecture/flideck-knowledge-base.md',
    api_reference: 'CLAUDE.md',
    schema: '/api/schema/manifest',
  },
};

/**
 * Create capabilities routes.
 * No dependencies needed - returns static capability description.
 */
export function createCapabilitiesRoutes(): Router {
  const router = Router();

  router.get('/', (_req, res) => {
    res.json(CAPABILITIES);
  });

  return router;
}
